version: '2'
services:
    web:
        volumes:
            - sessions:/var/tmp/sessions
        restart: always
        ports:
            - 80:80
        networks:
            - default
volumes:
    sessions:

networks:
    default:
